Modified mget and mget_by_index. If the request body json contains 'd…
dbmi-pitt/search-adaptor pull request #17
Opened 2022-11-02 15:49 UTC by DerekFurstPitt

Modified mget and mget_by_index. If the request body json contains 'docs', and 'docs' contains '_index', an error is raised prompting the specify the chosen index with a string parameter in mget_by_index.

2022-11-02 17:10 UTC, shirey approved these changes
Looks good!

2022-11-02 17:20 UTC, yuanzhou requested changes
@DerekFurstPitt can you update the error message to say

```
To target a specific index, use /<index>/mget
```
Because the end users have no idea of what `<index_without_prefix>` is. They don't know anything about the prefix that we use internally.

2022-11-02 18:48 UTC, DerekFurstPitt commented
@yuanzhou Good idea. this language has been updated

2022-11-03 02:32 UTC, yuanzhou approved these changes

2022-11-03 02:32 UTC, merged